services:
  api:
    image: itron1x/calendar-be
    restart: unless-stopped
    environment:
      - MONGODB_URL=${MONGODB_URL}
    container_name: calendar-api
    network_mode: host

  calendar:
    image: itron1x/calendar-fe
    restart: unless-stopped
    container_name: calendar
    network_mode: host