services:
  api:
    image: itron1x/calendar-be
    environment:
      - MONGODB_URL=${MONGODB_URL}
    container_name: calendar-api_c
    network_mode: host
    # ports:
    #   - 3000:3000/tcp

  calendar:
    image: itron1x/calendar-fe
    container_name: calendar_c
    network_mode: host
    # ports:
    # - 4000:4000/tcp